# Generated by Django 5.1.3 on 2024-12-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_passwordreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='jani_na_role',
            field=models.BooleanField(default=False),
        ),
    ]
