# Generated by Django 5.1.3 on 2024-12-03 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_jani_na_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='jani_na_role',
        ),
    ]
